In [ ]:
#numpy: it is a python library for numerical and scientific computations

In [1]:
my_list=[1,2,3,4,5]


In [3]:
from array import array
my_array=array("i",[1,2,3,4,5])

In [5]:
#numpy arrays
l=[1,1,2,3]
l


[1, 1, 2, 3]

In [7]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4])

In [19]:
type(arr)

numpy.ndarray

In [11]:
arr

array([1, 2, 3, 4])

In [13]:
type(arr)

numpy.ndarray

In [15]:
arr.ndim

1

In [21]:
arr.dtype

dtype('int32')

In [23]:
import numpy as np
array_new=np.array([1,2,3,4,5,6])

In [25]:
array_new+3

array([4, 5, 6, 7, 8, 9])

In [27]:
type(array_new)

numpy.ndarray

In [29]:
import numpy as np
my_num_array=np.array([1,2,3,4,5])

In [31]:
import numpy as np
my_numpy_array=np.array([1,2,3,4,5])

In [33]:
new_arr=my_numpy_array*3

In [36]:
new_arr

array([ 3,  6,  9, 12, 15])

In [38]:
type(my_numpy_array)

numpy.ndarray

In [44]:
my_array=np.array([1,2,3,4])
result=my_array*2
print(result)


[2 4 6 8]


In [48]:
arr

array([1, 2, 3, 4])

In [52]:

arr>2

array([False, False,  True,  True])

In [60]:
arr_2d=np.array([[0,1,2,3], [4,5,6,7],[8,9,0,5]])
arr_2d

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 5]])

In [62]:
arr_2d*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27,  0, 15]])

In [64]:
arr_2d+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11,  2,  7]])

In [66]:
arr_2d-1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8, -1,  4]])

In [68]:
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [72]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
matrix*4

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [76]:
matrix+8

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [88]:
import numpy as np
list_data=[1,2,3,4,5]
array_from_list=np.array(list_data)

In [94]:
list_data

[1, 2, 3, 4, 5]

In [96]:
type(list_data)

list

In [98]:
array_from_list

array([1, 2, 3, 4, 5])

In [100]:
type(array_from_list)

numpy.ndarray