In [3]:
import numpy as np
uniform=np.random.rand(3,3)
print("uniform distribution:\n",uniform)

uniform distribution:
 [[0.178995   0.15576704 0.15405681]
 [0.6322035  0.4791537  0.69399418]
 [0.24355711 0.27587836 0.48906482]]


In [5]:
#searching in arrays---using np.where

In [8]:
arr=np.array([1,2,3,4,5])
np.where(arr>3)

(array([3, 4], dtype=int64),)

In [13]:
np.where(arr==5)

(array([4], dtype=int64),)

In [14]:
##np.argmax/np.argmin---gives index of max and min value in array

In [15]:
arr=np.array([1,2,3,4])


In [16]:
np.argmin(arr)

0

In [17]:
np.argmax(arr)

3

In [ ]:
## np.searchsorted-----it describes index where the new value has to be stored in array

In [18]:
arr=np.array([1,2,5,8])

In [21]:
np.searchsorted(arr,4)

2

In [ ]:
##np.extract-----it gives values which are >/< than given condition

In [23]:
arr=np.array([1,2,3,4])

In [25]:
np.extract(arr>2,arr)

array([3, 4])

In [ ]:
## np.transpose------it transpose rows to column and vice versa

In [30]:
matrix=np.array([[1,2,3],
                 [3,4,5]])

In [31]:
np.transpose(matrix)

array([[1, 3],
       [2, 4],
       [3, 5]])

In [ ]:
###np.mean----it gives avg of given array

In [32]:
arr=np.array([1,2,3,4])

In [34]:
np.mean(arr)

2.5

In [35]:
##np.split----break array into smaller parts

In [36]:
arr=np.array([1,2,3,4,5,6,7,8])
np.split(arr,4)#it will split into 4 parts

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [38]:
np.split(arr,[3,4]) #it splits at 3rd index and 4th index otherthan this index value it will join all values.

[array([1, 2, 3]), array([4]), array([5, 6, 7, 8])]

In [54]:
matrix=np.array([[1,2,3,8],
                 [3,4,5,8],
                [5,9,8,7],
                [4,8,0,6]])

In [55]:
np.split(matrix,4,axis=1) #split columns

[array([[1],
        [3],
        [5],
        [4]]),
 array([[2],
        [4],
        [9],
        [8]]),
 array([[3],
        [5],
        [8],
        [0]]),
 array([[8],
        [8],
        [7],
        [6]])]

In [57]:
matrix=np.array([[1,2,3],
                 [3,4,5],
                 [3,3,3]])

In [58]:
np.split(matrix,3,axis=0)   #split rows

[array([[1, 2, 3]]), array([[3, 4, 5]]), array([[3, 3, 3]])]

In [ ]:
###np.sort---sort the array

In [61]:
arr=np.array([33,55,3,45,8])

In [62]:
np.sort(arr)

array([ 3,  8, 33, 45, 55])