In [1]:
import numpy as np
a33=np.ones((3,4))

In [2]:
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
a44=np.zeros((2,4))

In [4]:
a44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a55=np.eye(3)

In [6]:
a55

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
a66=np.arange(0,15)

In [8]:
a66

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
a77=np.linspace(0,9,7)

In [20]:
a77

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [21]:
arr8=np.random.rand(2,2)

In [22]:
arr8

array([[0.6454639 , 0.67299819],
       [0.14644754, 0.13210975]])

In [27]:
arr9=np.array([8,9,6,4])
print(arr9[0])
print(arr9[2])
print(arr9[-1])

8
6
4


In [29]:
matrix=np.array([[1,2,3],[4,5,6]])
print(matrix[1,2])
print(matrix[0,2])

6
3


In [31]:
arr=np.array([11,22,33,44,55])


In [32]:
print(arr[1:3])

[22 33]


In [35]:
print(arr[::-1])

[55 44 33 22 11]


In [39]:
print(arr[0::])

[11 22 33 44 55]


In [41]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])



In [60]:
print(matrix[2:,1:2])

[]


In [ ]:
print(matrix[

In [55]:
a=np.array([1,2,3,4])
b=a[0:2]


In [56]:
b

array([1, 2])

In [57]:
b[1]=22

In [58]:
b

array([ 1, 22])

In [59]:
a

array([ 1, 22,  3,  4])

In [61]:
###copy

In [62]:
a=np.array([1,2,8,9])
b=a[0:2].copy()

In [63]:
b

array([1, 2])

In [64]:
b[0]=3

In [65]:
b

array([3, 2])

In [66]:
a

array([1, 2, 8, 9])

In [ ]:
###shape that is rows and columns

In [69]:
arr=np.array([[1,2,3],[3,4,5],[7,8,9]])

In [70]:
arr.shape

(3, 3)

In [71]:
###reshape 

In [72]:
arr=np.arange(10)

In [73]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [76]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
arr.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [78]:
arr.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [81]:
###transpose


In [82]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [83]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])